{{- if not .Values.externalDatabase.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blockscout.fullname" . }}-db
  labels:
    {{- include "blockscout.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.externalDatabase.password | required "externalDatabase.password is required when not using existingSecret" | quote }}
{{- end }}
