apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nethermind.fullname" . }}-secrets
  labels:
    {{- include "nethermind.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.jwtSecret }}
  jwt-secret.txt: {{ .Values.secrets.jwtSecret | b64enc }}
  {{- else }}
  jwt-secret.txt: {{ randAlphaNum 64 | b64enc }}
  {{- end }}

