apiVersion: apps/v1
kind: Deployment
metadata:
  name: op-node
  namespace: mychain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: op-node
  template:
    metadata:
      labels:
        app: op-node
    spec:
      containers:
      - name: op-node
        image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.9.4
        ports:
        - containerPort: 9545
        env:
        - name: OP_NODE_L2_ENGINE_RPC
          value: "http://sequencer:8551"
