apiVersion: v1
kind: Service
metadata:
  name: {{ include "sequencer.fullname" . }}
  labels:
    {{- include "sequencer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.rpc }}
      targetPort: http
      protocol: TCP
      name: rpc
    - port: {{ .Values.service.ports.ws }}
      targetPort: ws
      protocol: TCP
      name: ws
    - port: {{ .Values.service.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "sequencer.selectorLabels" . | nindent 4 }}
    component: sequencer
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sequencer.fullname" . }}-headless
  labels:
    {{- include "sequencer.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.ports.rpc }}
      targetPort: http
      protocol: TCP
      name: rpc
    - port: {{ .Values.service.ports.ws }}
      targetPort: ws
      protocol: TCP
      name: ws
    - port: {{ .Values.service.ports.p2p }}
      targetPort: p2p
      protocol: TCP
      name: p2p
    - port: {{ .Values.service.ports.p2p }}
      targetPort: p2p-udp
      protocol: UDP
      name: p2p-udp
    - port: {{ .Values.service.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "sequencer.selectorLabels" . | nindent 4 }}
    component: sequencer

