# IPFS - Testnet Configuration

image:
  repository: 502713364895.dkr.ecr.us-east-1.amazonaws.com/jeju/ipfs
  tag: "testnet-latest"

replicaCount: 2

ingress:
  enabled: true
  hosts:
    - host: ipfs.testnet.jejunetwork.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ipfs-testnet-tls
      hosts:
        - ipfs.testnet.jejunetwork.org

persistence:
  enabled: true
  storageClass: "gp3"
  size: 100Gi

env:
  - name: IPFS_GATEWAY_URL
    value: "https://ipfs.testnet.jejunetwork.org"
  - name: X402_ENABLED
    value: "true"

