apiVersion: v1
kind: Service
metadata:
  name: {{ include "farcaster-hubble.fullname" . }}
  labels:
    {{- include "farcaster-hubble.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.grpc.port }}
      targetPort: grpc
      protocol: {{ .Values.service.grpc.protocol }}
      name: grpc
    - port: {{ .Values.service.gossip.port }}
      targetPort: gossip
      protocol: {{ .Values.service.gossip.protocol }}
      name: gossip
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: {{ .Values.service.http.protocol }}
      name: http
  selector:
    {{- include "farcaster-hubble.selectorLabels" . | nindent 4 }}
---
# Headless service for gossip peer discovery
apiVersion: v1
kind: Service
metadata:
  name: {{ include "farcaster-hubble.fullname" . }}-gossip
  labels:
    {{- include "farcaster-hubble.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.gossip.port }}
      targetPort: gossip
      protocol: UDP
      name: gossip-udp
    - port: {{ .Values.service.gossip.port }}
      targetPort: gossip
      protocol: TCP
      name: gossip-tcp
  selector:
    {{- include "farcaster-hubble.selectorLabels" . | nindent 4 }}

