apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxy-coordinator.fullname" . }}-secrets
  labels:
    {{- include "proxy-coordinator.labels" . | nindent 4 }}
type: Opaque
data:
  coordinator-private-key: {{ .Values.config.coordinatorPrivateKey | b64enc | quote }}
  {{- if .Values.config.externalProviders.brightdata.enabled }}
  brightdata-username: {{ .Values.config.externalProviders.brightdata.username | b64enc | quote }}
  brightdata-password: {{ .Values.config.externalProviders.brightdata.password | b64enc | quote }}
  {{- end }}

