{{- if .Values.relay.enabled }}
{{- if .Values.relay.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "messaging.fullname" . }}-relay
  labels:
    {{- include "messaging.labels" . | nindent 4 }}
    app.kubernetes.io/component: relay
  {{- with .Values.relay.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
---
{{- if .Values.kms.enabled }}
{{- if .Values.kms.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "messaging.fullname" . }}-kms
  labels:
    {{- include "messaging.labels" . | nindent 4 }}
    app.kubernetes.io/component: kms
  {{- with .Values.kms.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}

