{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dws-registry.fullname" . }}
  labels:
    {{- include "dws-registry.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . }}
    {{- end }}
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
---
{{- if and .Values.ipfs.enabled .Values.ipfs.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dws-registry.fullname" . }}-ipfs
  labels:
    {{- include "dws-registry.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.ipfs.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.ipfs.persistence.size }}
{{- end }}

