version: '3'

services:
  eqlite_bp_0:
    image: eqlite/eqlite:latest
    container_name: eqlite_bp_0
    restart: always
    ports:
      - '11099:4661'
      - '12099:4665'
    environment:
      EQLITE_ROLE: blockproducer
      EQLITE_CONF: ./node_0/config.yaml
      METRIC_WEB_ADDR: '0.0.0.0:4665'
    volumes:
      - ./test/service/node_0/:/app/node_0/
    networks:
      default:
        ipv4_address: 172.254.1.2
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '10'
  eqlite_bp_1:
    image: eqlite/eqlite:latest
    container_name: eqlite_bp_1
    restart: always
    ports:
      - '11100:4661'
      - '12100:4665'
    environment:
      EQLITE_ROLE: blockproducer
      EQLITE_CONF: ./node_1/config.yaml
      METRIC_WEB_ADDR: '0.0.0.0:4665'
    volumes:
      - ./test/service/node_1/:/app/node_1/
    networks:
      default:
        ipv4_address: 172.254.1.3
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '10'
  eqlite_bp_2:
    image: eqlite/eqlite:latest
    container_name: eqlite_bp_2
    restart: always
    ports:
      - '11101:4661'
      - '12101:4665'
    environment:
      EQLITE_ROLE: blockproducer
      EQLITE_CONF: ./node_2/config.yaml
      METRIC_WEB_ADDR: '0.0.0.0:4665'
    volumes:
      - ./test/service/node_2/:/app/node_2/
    networks:
      default:
        ipv4_address: 172.254.1.4
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '10'
  eqlite_miner_0:
    image: eqlite/eqlite:latest
    container_name: eqlite_miner_0
    restart: always
    ports:
      - '11102:4661'
      - '12102:4665'
    environment:
      EQLITE_ROLE: miner
      EQLITE_CONF: ./node_miner_0/config.yaml
      METRIC_WEB_ADDR: '0.0.0.0:4665'
    volumes:
      - ./test/service/node_miner_0/:/app/node_miner_0/
    networks:
      default:
        ipv4_address: 172.254.1.5
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '10'
  eqlite_miner_1:
    image: eqlite/eqlite:latest
    container_name: eqlite_miner_1
    restart: always
    ports:
      - '11103:4661'
      - '12103:4665'
    environment:
      EQLITE_ROLE: miner
      EQLITE_CONF: ./node_miner_1/config.yaml
      METRIC_WEB_ADDR: '0.0.0.0:4665'
    volumes:
      - ./test/service/node_miner_1/:/app/node_miner_1/
    networks:
      default:
        ipv4_address: 172.254.1.6
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '10'
  eqlite_miner_2:
    image: eqlite/eqlite:latest
    container_name: eqlite_miner_2
    restart: always
    ports:
      - '11104:4661'
      - '12104:4665'
    environment:
      EQLITE_ROLE: miner
      EQLITE_CONF: ./node_miner_2/config.yaml
      METRIC_WEB_ADDR: '0.0.0.0:4665'
    volumes:
      - ./test/service/node_miner_2/:/app/node_miner_2/
    networks:
      default:
        ipv4_address: 172.254.1.7
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '10'
  eqlite_adapter:
    image: eqlite/eqlite:latest
    container_name: eqlite_adapter
    restart: always
    ports:
      - '11105:4661'
    environment:
      EQLITE_ROLE: adapter
      EQLITE_CONF: ./node_adapter/config.yaml
      EQLITE_ADAPTER_ADDR: 0.0.0.0:4661
    volumes:
      - ./test/service/node_adapter/:/app/node_adapter/
    networks:
      default:
        ipv4_address: 172.254.1.8
  eqlite_mysql_adapter:
    image: eqlite/eqlite:latest
    container_name: eqlite_mysql_adapter
    restart: always
    ports:
      - '11107:4664'
    command: ['-listen', '0.0.0.0:4664']
    environment:
      EQLITE_ROLE: mysql-adapter
      EQLITE_CONF: ./node_mysql_adapter/config.yaml
    volumes:
      - ./test/service/node_mysql_adapter/:/app/node_mysql_adapter/
    networks:
      default:
        ipv4_address: 172.254.1.10
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '10'
  eqlite_explorer:
    image: eqlite/eqlite:latest
    container_name: eqlite_explorer
    restart: always
    ports:
      - '11108:4663'
    environment:
      EQLITE_ROLE: explorer
      EQLITE_CONF: ./node_explorer/config.yaml
      EQLITE_OBSERVER_ADDR: 0.0.0.0:4663
    volumes:
      - ./test/service/node_explorer/:/app/node_explorer/
    networks:
      default:
        ipv4_address: 172.254.1.9
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
  eqlite_fn_0:
    image: eqlite/eqlite:latest
    container_name: eqlite_fn_0
    restart: always
    ports:
      - '11110:8546'
    command: ['-wsapi', ':8546']
    # entrypoint: ["sh"]
    environment:
      EQLITE_ROLE: blockproducer
      EQLITE_CONF: ./fullnode_0/config.yaml
    volumes:
      - ./test/service/fullnode_0/:/app/fullnode_0/
    networks:
      default:
        ipv4_address: 172.254.1.11
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.254.1.0/24
